title = "rosie yohannan's profile and blog"
baseURL = 'https://example.org/'
languageCode = 'en-us'

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[security]
[security.exec]
allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^asciidoctor$']

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
mainSections = ["posts"]
text_color = "dark-blue"
author = "Rosie Yohannan" # default author, override via `author` in a posts front matter
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
custom_css = ["ananke/css/custom.css", "css/rouge.css"]
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-light-green"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 3

[params.ananke.social.follow]
networks = [
  "linkedin"
]

[params.ananke.social.linkedin]
username = "rosieyo"

[markup]
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
        source-highlighter = 'rouge'

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
